### ISSUE TITLE
mobileID does not work with Lithuanian numbers

### ISSUE THREAD

**Issue by rrrluk** [codeborne/mobileid#10]
372 always gets added

    if (phone != null) {
      if (phone.startsWith("+")) phone = phone.substring(1);
      if (!phone.startsWith("372")) phone = "372" + phone;
    }

**Comment by asolntsev** [comment]
@rrrluk Wow, I didn't think that somebody uses our library in Lithuania!
Thank you for reporting the issue. 

Fixed and released version 1.4 (will appear in maven central repository in few hours).

**Comment by rrrluk** [comment]
Works, awesome, thank you!
